# specify which database and adapter to use for which environment

development:
  adapter: postgresql
  database: laugh-tracks-development

test:
  adapter: postgresql
  database: laugh-tracks-test

production:
  adapter: postgresql
  database: laugh-tracks-production

